# This is a sample command please replace with correct command
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_erp
    username: root
    password: root1234
#    hikari:
#      schema: systempg

  jpa:
    hibernate:
      ddl-auto: update
eurek:
  client:
    enabled: false

jwt:
  token:
    validity: 36000000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization

server:
  port: 8003
  error:
    include-message: always